#include <stdint.h>
#define EXP_QUERIES                     0x000
#define EXP_WHITESPACE                  0x001
#define EXP_SELECT                      0x002
#define EXP_SELECT_EXPR_LIST            0x003
#define EXP_IDENTIFIER                  0x004
#define EXP_EXPR                        0x005
#define EXP_SELECT_EXPR                 0x006
#define EXP_SUBQUERY                    0x007
#define EXP_BOOLEAN_PRIMARY             0x008
#define EXP_PREDICATE                   0x009
#define EXP_COMPARISON_OPERATOR         0x00A
#define EXP_NULL                        0x00B
#define EXP_BIT_EXPR                    0x00C
#define EXP_SIMPLE_EXPR                 0x00D
#define EXP_OPERATIONS                  0x00E
#define EXP_IDENTIFIER_EXPR             0x00F
#define EXP_LITERAL                     0x010
#define EXP_HEX                         0x011
#define EXP_BIT                         0x012
#define EXP_BOOLEAN                     0x013
#define EXP_STRING                      0x014
#define EXP_REAL                        0x015
#define EXP_UNKNOWN                     0x016
#define EXP_TRUE                        0x017
#define EXP_FALSE                       0x018
#define EXP_INTEGER                     0x019
#define EXP_SIGNED_INT                  0x01A
#define EXP_UNSIGNED_INT                0x01B
#define EXP_SIGN                        0x01C
#define EXP_EXPONENT                    0x01D
#define EXP_KEYWORDS                    0x01E
#define EXP_SINGLE_QUOTE_STRING         0x01F
#define EXP_DOUBLE_QUOTE_STRING         0x020
#define EXP_QUERY_DELIMITER             0x021
#define EXP_COMMENT                     0x022
#define EXP_BLOCK_COMMENT               0x023
#define EXP_SINGLE_COMMENT              0x024
#define EXP_LEFT_COMMENT                0x025
#define EXP_RIGHT_COMMENT               0x026
#define EXP_INLINE_COMMENT              0x027
#define EXP_END_OF_LINE                 0x028
#define EXP_CATCH_ALL                   0x029
#define STR_SELECT                      0x02A
#define STR_FROM                        0x02B
#define STR_PERIOD                      0x02C
#define STR_AS                          0x02D
#define STR_WHERE                       0x02E
#define STR_COMMA                       0x02F
#define STR_LEFT_PAREN                  0x030
#define STR_RIGHT_PAREN                 0x031
#define STR_IS                          0x032
#define STR_NOT                         0x033
#define STR_NULL_EQUAL                  0x034
#define STR_ALL                         0x035
#define STR_ANY                         0x036
#define STR_IN                          0x037
#define STR_BETWEEN                     0x038
#define STR_AND                         0x039
#define STR_LIKE                        0x03A
#define STR_ESCAPE                      0x03B
#define STR_LOGICAL_OR                  0x03C
#define STR_LOGICAL_AND                 0x03D
#define STR_LT                          0x03E
#define STR_GT                          0x03F
#define STR_PLUS                        0x040
#define STR_MINUS                       0x041
#define STR_TIMES                       0x042
#define STR_DIVIDE                      0x043
#define STR_DIV                         0x044
#define STR_MOD                         0x045
#define STR_MODULUS                     0x046
#define STR_SPACE                       0x047
#define STR_UNKNOWN                     0x048
#define STR_0                           0x049
#define STR_X                           0x04A
#define STR_9                           0x04B
#define STR_A                           0x04C
#define STR_F                           0x04D
#define STR_B                           0x04E
#define STR_1                           0x04F
#define STR_NULL                        0x050
#define STR_TRUE                        0x051
#define STR_FALSE                       0x052
#define STR_E                           0x053
#define STR_Z                           0x054
#define STR_DOLLAR_SIGN                 0x055
#define STR_UNDERSCORE                  0x056
#define STR_ON                          0x057
#define STR_OR                          0x058
#define STR_XOR                         0x059
#define STR_LIMIT                       0x05A
#define STR_HAVING                      0x05B
#define STR_GROUP                       0x05C
#define STR_BY                          0x05D
#define STR_ORDER                       0x05E
#define STR_SINGLE_QUOTE                0x05F
#define STR_DOUBLE_QUOTE                0x060
#define STR_SEMICOLON                   0x061
#define STR_EQUALS                      0x062
#define STR_NEGATE                      0x063
#define STR_NEW_LINE                    0x064
#define STR_R                           0x065
#define STR_TAB                         0x066

const char *debug_str[103];



uint16_t *pattern[103];
