// this holds the string you are tokenizing
typedef struct node_t {
  int len;
  int pos;
  int OK;
  int depth;
  char *value;
  struct stack_t *stack;
} node_t;
node_t *match_select(node_t * n, const char *last_method);
node_t *match_expr(node_t * n, const char *last_method);
node_t *match_boolean_primary(node_t * n, const char *last_method);
node_t *match_predicate(node_t * n, const char *last_method);
node_t *match_bit_expr(node_t * n, const char *last_method);
node_t *match_operations(node_t * n, const char *last_method);
node_t *match_complex_expr(node_t * n, const char *last_method);
node_t *match_simple_expr(node_t * n, const char *last_method);
node_t *match_literal(node_t * n, const char *last_method);
node_t *match_YEARS(node_t * n, const char *last_method);
node_t *match_QUARTERS(node_t * n, const char *last_method);
node_t *match_MONTHS(node_t * n, const char *last_method);
node_t *match_WEEKS(node_t * n, const char *last_method);
node_t *match_DAYS(node_t * n, const char *last_method);
node_t *match_HOURS(node_t * n, const char *last_method);
node_t *match_MINUTES(node_t * n, const char *last_method);
node_t *match_SECONDS(node_t * n, const char *last_method);
node_t *match_MICROSECONDS(node_t * n, const char *last_method);
node_t *match_MICROSECOND(node_t * n, const char *last_method);
node_t *match_SECOND(node_t * n, const char *last_method);
node_t *match_MINUTE(node_t * n, const char *last_method);
node_t *match_HOUR(node_t * n, const char *last_method);
node_t *match_DAY(node_t * n, const char *last_method);
node_t *match_WEEK(node_t * n, const char *last_method);
node_t *match_MONTH(node_t * n, const char *last_method);
node_t *match_QUARTER(node_t * n, const char *last_method);
node_t *match_YEAR(node_t * n, const char *last_method);
node_t *match_SECOND_MICROSECOND(node_t * n, const char *last_method);
node_t *match_MINUTE_MICROSECOND(node_t * n, const char *last_method);
node_t *match_MINUTE_SECOND(node_t * n, const char *last_method);
node_t *match_HOUR_MICROSECOND(node_t * n, const char *last_method);
node_t *match_HOUR_SECOND(node_t * n, const char *last_method);
node_t *match_HOUR_MINUTE(node_t * n, const char *last_method);
node_t *match_DAY_MICROSECOND(node_t * n, const char *last_method);
node_t *match_DAY_SECOND(node_t * n, const char *last_method);
node_t *match_DAY_MINUTE(node_t * n, const char *last_method);
node_t *match_DAY_HOUR(node_t * n, const char *last_method);
node_t *match_YEAR_MONTH(node_t * n, const char *last_method);
node_t *match_interval_expr(node_t * n, const char *last_method);
node_t *match_comment(node_t * n, const char *last_method);
node_t *match_block_comment(node_t * n, const char *last_method);
node_t *match_single_comment(node_t * n, const char *last_method);
node_t *match_left_comment(node_t * n, const char *last_method);
node_t *match_right_comment(node_t * n, const char *last_method);
node_t *match_inline_comment(node_t * n, const char *last_method);
node_t *match_unknown(node_t * n, const char *last_method);
node_t *match_hex(node_t * n, const char *last_method);
node_t *match_bit(node_t * n, const char *last_method);
node_t *match_null(node_t * n, const char *last_method);
node_t *match_true(node_t * n, const char *last_method);
node_t *match_false(node_t * n, const char *last_method);
node_t *match_boolean(node_t * n, const char *last_method);
node_t *match_real(node_t * n, const char *last_method);
node_t *match_integer(node_t * n, const char *last_method);
node_t *match_signed_int(node_t * n, const char *last_method);
node_t *match_unsigned_int(node_t * n, const char *last_method);
node_t *match_sign(node_t * n, const char *last_method);
node_t *match_exponent(node_t * n, const char *last_method);
node_t *match_identifier(node_t * n, const char *last_method);
node_t *match_alpha(node_t * n, const char *last_method);
node_t *match_whitespace(node_t * n, const char *last_method);
node_t *match_single_quote_string(node_t * n, const char *last_method);
node_t *match_double_quote_string(node_t * n, const char *last_method);
node_t *match_string(node_t * n, const char *last_method);
node_t *match_select_expr(node_t * n, const char *last_method);
node_t *match_end_of_line(node_t * n, const char *last_method);
node_t *match_comparison_operator(node_t * n, const char *last_method);
node_t *match_not_whitespace(node_t * n, const char *last_method);
node_t *match_function(char *data);
